name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Check formatting
      run: cargo fmt -- --check

    - name: Run linting
      run: cargo clippy -- -D warnings

    - name: Run tests
      run: cargo test
